name: Build EXE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
        
    - name: Create database file if not exists
      working-directory: ./src
      run: |
        if not exist stok_takip.db (
          echo "Creating empty database file"
          sqlite3 stok_takip.db "VACUUM;"
        )
        
    - name: Build EXE with PyInstaller
      working-directory: ./src
      run: |
        pyinstaller --onefile --windowed --name StokTakip --add-data "stok_takip.db;." stok_takip.py
        
    - name: Verify EXE file
      working-directory: ./src
      run: |
        if not exist dist\StokTakip.exe (
          echo "Error: EXE file not created!"
          exit 1
        )
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: StokTakip
        path: |
          src/dist/StokTakip.exe
          src/stok_takip.db