name: Build EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ttkthemes tkcalendar pandas pyinstaller
        
    - name: Create database file
      working-directory: ./src
      run: |
        if (!(Test-Path -Path "stok_takip.db")) {
          sqlite3 stok_takip.db "VACUUM;"
          Write-Output "Database file created"
        }
        
    - name: Build with PyInstaller
      working-directory: ./src
      run: |
        pyinstaller --onefile --windowed --name StokTakip --add-data "stok_takip.db;." stok_takip.py
        
    - name: Check build artifacts
      working-directory: ./src
      run: |
        if (!(Test-Path -Path "dist\StokTakip.exe")) {
          Write-Output "Build failed - listing directory contents:"
          Get-ChildItem
          Get-ChildItem -Path dist
          exit 1
        }
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: StokTakip
        path: |
          src/dist/StokTakip.exe
          src/stok_takip.db
