name: Build EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python with Tkinter
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        # Tkinter desteği için gerekli paketler
        choco install -y python --params "/InstallTkinter=1"
        refreshenv
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ttkthemes tkcalendar pandas pyinstaller
        
    - name: Create database file
      working-directory: ./src
      run: |
        if not exist stok_takip.db (
          echo "Creating empty database file"
          sqlite3 stok_takip.db "VACUUM;"
        )
        
    - name: Build with PyInstaller (debug mode)
      working-directory: ./src
      run: |
        pyinstaller --onefile --windowed --name StokTakip --add-data "stok_takip.db;." --debug all stok_takip.py
        
    - name: Check build artifacts
      working-directory: ./src
      run: |
        if not exist dist\StokTakip.exe (
          echo "Build failed - listing directory contents:"
          dir
          dir dist
          exit 1
        )
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: StokTakip
        path: |
          src/dist/StokTakip.exe
          src/stok_takip.db
